### ISSUE TITLE
last.fm fetch period

### ISSUE THREAD

**Issue by aleclol** [obrhoff/MusaicFM#37]
When selecting the 7 days period for last.fm, it automatically resets to Overview when System Preferences is closed.

**Comment by obrhoff** [comment]
Thanks for reporting. I will take a look at it.

**Comment by obrhoff** [comment]
Hey. I fixed this issue in lastest release.

**Comment by aleclol** [comment]
Awesome! Thank you so much ❤️

**Comment by josephtannenbaum** [comment]
Hi! I'm still seeing this issue in 1.2.5 downloaded with Homebrew. I'm on Mac Sonoma 14.3
